# Generated by Django 5.2 on 2025-04-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("survey_ID", models.AutoField(primary_key=True, serialize=False)),
                ("survey_q1", models.CharField(max_length=255)),
                ("survey_q2", models.CharField(max_length=255)),
                ("survey_q5", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "survey",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_ID", models.AutoField(primary_key=True, serialize=False)),
                ("user_dateofbirth", models.DateField()),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("user_consent", models.BooleanField()),
                ("user_first_name", models.CharField(max_length=255)),
                ("user_last_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
