# Generated by Django 4.2.20 on 2025-05-05 15:14

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("survey_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "survey_q1",
                    models.CharField(
                        choices=[
                            ("Multiple times a day", "Multiple times a day"),
                            ("Once a day", "Once a day"),
                            ("A few times a week", "A few times a week"),
                            ("Rarely", "Rarely"),
                            ("Do Not Know", "Do Not Know"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "survey_q2",
                    models.CharField(
                        choices=[
                            (
                                "I struggle to identify UPFs in foods",
                                "I struggle to identify UPFs in foods",
                            ),
                            (
                                "I don't have time to cook from scratch",
                                "I don't have time to cook from scratch",
                            ),
                            (
                                "Healthy food is too expensive",
                                "Healthy food is too expensive",
                            ),
                            (
                                "I crave processed food too much",
                                "I crave processed food too much",
                            ),
                            (
                                "I don't know where to start",
                                "I don't know where to start",
                            ),
                        ],
                        max_length=80,
                    ),
                ),
                ("survey_q3", models.BooleanField()),
                ("survey_q4", models.BooleanField()),
                (
                    "survey_q5",
                    models.CharField(
                        choices=[
                            (
                                "Reduce my ultra-processed food intake",
                                "Reduce my ultra-processed food intake",
                            ),
                            (
                                "Learn more about ultra-processed food",
                                "Learn more about ultra-processed food",
                            ),
                            (
                                "Eat more whole, minimally processed foods",
                                "Eat more whole, minimally processed foods",
                            ),
                            (
                                "Improve my overall nutrition and health",
                                "Improve my overall nutrition and health",
                            ),
                            (
                                "Track how much ultra-processed food I consume",
                                "Track how much ultra-processed food I consume",
                            ),
                            (
                                "Understand food labels and processing levels better",
                                "Understand food labels and processing levels better",
                            ),
                            (
                                "Discover hidden ultra processed ingredients in my diet",
                                "Discover hidden ultra processed ingredients in my diet",
                            ),
                            (
                                "Find healthier alternatives to my favourite processed foods",
                                "Find healthier alternatives to my favourite processed foods",
                            ),
                            (
                                "Get personalised food recommendations based on my diet",
                                "Get personalised food recommendations based on my diet",
                            ),
                        ],
                        max_length=80,
                    ),
                ),
            ],
            options={
                "db_table": "survey",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("consent", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
