# Generated by Django 5.2 on 2025-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                ("scan_ID", models.AutoField(primary_key=True, serialize=False)),
                ("scan_date", models.DateTimeField()),
                ("scan_product_name", models.CharField(max_length=255)),
                ("scan_nova_score", models.IntegerField()),
            ],
            options={
                "db_table": "scan",
                "managed": False,
            },
        ),
    ]
